config/routes.rb
Rails.application.routes.draw do
  get 'subscribe/book_slot'
  get 'subscribe/view_slot'

  devise_for :users
  resources :sections
  resources :courses
  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :sections
  has_many :subscribe
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :user_id, :course_id, presence: true

  @allowed_slots = ["6:00 am", "7:00 am", "6:00 pm", "7:00 pm"]
  validates :time_slot, :inclusion=> { :in => @allowed_slots }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
           

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:edit, :update, :destroy]
    before_action :authenticate_user!


  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new(section_params)
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:header, :description, :course_id)
    end
end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController

  def view_slot
    @courses = Course.all.includes(:subscribe)
  end

  def book_slot
    Subscribe.create(:user_id => current_user.id, :course_id => params[:course_id], :time_slot => params[:slot])
    @courses = Course.all.includes(:subscribe)
    redirect_to subscribe_view_slot_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subscribe_helper.rb
module SubscribeHelper
end

app/views/courses/_form.html.erb
<%= form_for @course, :html => { :class => "form-horizontal course" } do |f| %>

  <% if @course.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                courses_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/courses/edit.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/index.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_on) %></th>
      <th><%= model_class.human_attribute_name(:sections) %></th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.name, course_path(course) %></td>
        <td><%=l course.created_at.to_date %></td>
        <% course.sections.each do |section| %>
          <td><%= section.header %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.Create Course', :default => t("helpers.links.create_course")),
            new_course_path,
            :class => 'btn btn-primary' %>

app/views/courses/new.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/show.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @course.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Sections) %>:</strong></dt>
  <% @course.sections.each do |sec| %>
    <dd><%= sec.header %></dd>
  <% end %>
  
<br/><br/>
  <%= link_to t('.new', :default => t("helpers.links.add_section")),
            new_section_path(:section => {:course_id => @course.id}),
            :class => 'btn btn-primary' %>
</dl>



<%= link_to t('.back', :default => t("helpers.links.back")),
              courses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_course_path(@course), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              course_path(@course),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>

<%= nav_bar fixed: :top, brand: "Course Manager" do %>
  <%if (current_user)%>
    <%= menu_group pull: :left do %>
      <%= menu_item "Courses", courses_path, :style=>'font-weight: bold;' %>
      <%= menu_item "Subscribe Course", subscribe_view_slot_path, :style=>'font-weight: bold;' %>
    <% end %>
    <%= menu_group pull: :right do %>
      <%= menu_item "Logout", destroy_user_session_path, :style=>'font-weight: bold;', :method => :delete %>
    <% end %>
  <% end %>
<% end %>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>

</body>
</html>

app/views/sections/_form.html.erb
<%= form_for @section, :html => { :class => "form-horizontal section" } do |f| %>

  <% if @section.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @section.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :header, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :header, :class => 'form-control' %>
    </div>
    <%=f.error_span(:header) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :course_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :course_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:course_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sections_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/sections/edit.html.erb
<%- model_class = Section -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sections/index.html.erb
<%- model_class = Section -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:header) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:course_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= link_to section.id, section_path(section) %></td>
        <td><%= section.header %></td>
        <td><%= section.description %></td>
        <td><%= section.course_id %></td>
        <td><%=l section.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      section_path(section), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_section_path(section), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      section_path(section),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sections/new.html.erb
<%- model_class = Section -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sections/show.html.erb
<%- model_class = Section -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:header) %>:</strong></dt>
  <dd><%= @section.header %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @section.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:course_id) %>:</strong></dt>
  <dd><%= @section.course_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              course_path(@section.course), :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_section_path(@section), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              section_path(@section),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/subscribe/book_slot.html.erb
<h1>Subscribe#book_slot</h1>
<p>Find me in app/views/subscribe/book_slot.html.erb</p>

app/views/subscribe/view_slot.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="4">Slots</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <% booked_slots = course.subscribe.where(:user_id => current_user.id).collect{|s| s.time_slot}

        ["6:00 am", "7:00 am", "6:00 pm", "7:00 pm"].each do |slot|
          if booked_slots.include? slot
        %>
            <td><%=slot%></td>
          <% else %>
            <td><%= link_to "#{slot}", subscribe_book_slot_path(:course_id => course.id, :slot => slot), :class => 'btn btn-default btn-xs' %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>